authors:
  Phil:
    name: Philip Jorgensen
    description: Deployment Expert
    avatar: img/fav/favicon-32x32.png
  Thad:
    name: Thad Lawson
    description: Deployment Expert
    avatar: img/fav/favicon-32x32.png
  Joe:
    name: Joe Parker
    description: Team Leader
    avatar: img/fav/favicon-32x32.png
  Devin:
    name: Devin McDermott
    description: Software Developer
    avatar: img/fav/favicon-32x32.png